# -*- coding: utf-8 -*-
"""myname.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fv32vmSmpkVSqXDVwx4vp4A-Ho6eEqQH
"""

print('Wen Kai')